### ISSUE TITLE
delete from after the cursor to the next word?

### ISSUE THREAD

**Issue by aaylward** [wikitopian/hardmode#26]
Howdy,

In hardmode, I would like to delete from _after_ the cursor until the next word starts, but I can't seem to find a nice way.

If I have:

`PARAMETER      : value`

and I want to remove the space between the `PARAMETER` and the `:`

to yield: 

`PARAMETER: value`

Currently, I'm doing a `w` to jump to the `:`, then `dTR` does the job, but it seems like it should be possible to achieve the same effect without jumping past where I want to go and deleting backwards. Anyone have any ideas?

This might be a good candidate for https://github.com/wikitopian/hardmode/issues/22 :)

**Comment by ghost** [comment]
Just press `f<SPACE>x`. f<SPACE> goes to the first space character, which in this case is the one after `PARAMETER`. `x` deletes the character under the cursor, which also works with invisible characters.

**Comment by belkka** [comment]
It is better to use `wX`
`X` deletes the character before the cursor
^_^
