### ISSUE TITLE
Activating hardmode then opening a new file re-initialises hjkl keybindings

### ISSUE THREAD

**Issue by mattfield** [wikitopian/hardmode#28]
If you activate hardmode then open a new file, the new file uses the hjkl keybindings rather than honouring hardmode. If you `ctrl-o` back to the previous file, hardmode is still active. Is it possible to have hardmode persist for the session rather than per buffer? I'd submit a patch for this but my VimScript foo is weak!

**Comment by mkonecny** [comment]
Read the readme again. There is a way to make it persistent..

autocmd VimEnter,BufNewFile,BufReadPost \* silent! call HardMode()

**Comment by mattfield** [comment]
You're absolutely right, thanks.
