### ISSUE TITLE
Add beginner mode which only disables arrow keys

### ISSUE THREAD

**Issue by wikitopian** [wikitopian/hardmode#8]
@dsanson added a useful "beginner mode" for wannabes who aren't hardcore enough for hard mode.

Now we'll need to add an "extreme" mode!

**Comment by dsanson** [comment]
Lol. I think 'beginner mode' should be renamed 'wannabe mode'. Should I package up a pull request?

**Comment by ghost** [comment]
Slightly-less-weakling mode sounds good
